using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace MatchingService.Tests.Support;

/// <summary>
/// Stands in for Item Service's HTTP surface (GET api/items/{lost|found}/{id} and
/// GET api/items/{lost|found}/mine), the two endpoints ClaimItemClient calls. Responses are canned
/// per request rather than generated by a real ASP.NET Core host, matching Story 1's pattern of
/// faking exactly one collaborator per test class. JSON is written camelCase with
/// PropertyNameCaseInsensitive off, mirroring Item Service's own JsonSerializerOptions
/// (Program.cs: PropertyNamingPolicy = CamelCase) exactly, so a test fixture that would fail to
/// deserialize against the real service also fails here.
/// Beyond canned success/status responses, this can also simulate the three ways a real Item Service
/// call can fail below the HTTP-status level: a malformed body, a transport failure, and a request
/// that never completes (a timeout), so ClaimItemClient's own exception mapping can be tested too.
/// </summary>
public sealed class FakeItemServiceHandler : HttpMessageHandler
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    private readonly Dictionary<string, Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>>> _routes =
        new(StringComparer.Ordinal);

    // Records every request path this handler actually received, for assertions on what ClaimItemClient sent.
    public List<string> ReceivedPaths { get; } = [];
    public List<string?> ReceivedAuthorizationHeaders { get; } = [];

    // Registers a canned JSON response for one exact path, e.g. "api/items/lost/{id}".
    public FakeItemServiceHandler RespondWithJson(
        string path, HttpStatusCode status, object body)
    {
        _routes[path] = (_, _) => Task.FromResult(new HttpResponseMessage(status)
        {
            Content = JsonContent.Create(body, options: JsonOptions)
        });

        return this;
    }

    // Registers a bare status code with no body, for the 401/403/404/5xx mapping tests.
    public FakeItemServiceHandler RespondWithStatus(
        string path, HttpStatusCode status)
    {
        _routes[path] = (_, _) => Task.FromResult(new HttpResponseMessage(status));
        return this;
    }

    // A 200 whose body is not valid JSON at all, for GetJsonAsync's JsonException -> 503 mapping.
    public FakeItemServiceHandler RespondWithMalformedBody(string path)
    {
        _routes[path] = (_, _) => Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK)
        {
            Content = new StringContent("{ this is not valid json", System.Text.Encoding.UTF8, "application/json")
        });

        return this;
    }

    // The transport itself fails (DNS failure, connection refused, etc.), for GetJsonAsync's HttpRequestException -> 503 mapping.
    public FakeItemServiceHandler FailWithConnectionError(string path)
    {
        _routes[path] = (_, _) => throw new HttpRequestException("Simulated connection failure.");
        return this;
    }

    /* Never responds until the caller's own HttpClient.Timeout cancels the request. GetJsonAsync must
       tell this apart from the caller's own cancellationToken being cancelled (that case is not an
       error at all, see ClaimItemClient) and map it to 503 instead. */
    public FakeItemServiceHandler NeverRespond(string path)
    {
        _routes[path] = async (_, cancellationToken) =>
        {
            await Task.Delay(Timeout.InfiniteTimeSpan, cancellationToken);
            throw new InvalidOperationException("Unreachable: the delay above never completes normally.");
        };

        return this;
    }

    protected override async Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        var path = request.RequestUri!.AbsolutePath.TrimStart('/');
        ReceivedPaths.Add(path);
        ReceivedAuthorizationHeaders.Add(
            request.Headers.Authorization?.ToString());

        if (_routes.TryGetValue(path, out var respond))
        {
            return await respond(request, cancellationToken);
        }

        return new HttpResponseMessage(HttpStatusCode.NotFound);
    }

    // A minimal, valid ItemReport-shaped body. Callers override only the fields their test cares about.
    public static object Report(
        Guid id,
        Guid userId,
        string status = "ACTIVE",
        string title = "Blue backpack",
        string category = "Bags",
        string description = "A blue backpack with a front pocket.",
        string dateLost = "2026-09-01",
        string dateFound = "2026-09-01",
        string lastKnownLocation = "Malabe",
        string locationFound = "Malabe",
        List<string>? photoUrls = null) => new
        {
            id,
            userId,
            title,
            category,
            description,
            status,
            dateLost,
            dateFound,
            lastKnownLocation,
            locationFound,
            photoUrls = photoUrls ?? []
        };
}
